---
- name: Import Docker tasks
  ansible.builtin.import_tasks: docker.yml

- name: Import Podman tasks
  ansible.builtin.import_tasks: podman.yml

- name: Import Rustup tasks
  ansible.builtin.import_tasks: rustup.yml

- name: Import Go tasks
  ansible.builtin.import_tasks: go.yml
