---
- name: Import Docker tasks
  ansible.builtin.import_tasks: docker.yml

- name: Import Podman tasks
  ansible.builtin.import_tasks: podman.yml

- name: Import Rustup tasks
  ansible.builtin.import_tasks: rustup.yml

- name: Import Go tasks
  ansible.builtin.import_tasks: go.yml

- name: Import nvm tasks
  ansible.builtin.import_tasks: nvm.yml

- name: Import gh tasks
  ansible.builtin.import_tasks: gh.yml

- name: Import OpenCode tasks
  ansible.builtin.import_tasks: opencode.yml

- name: Import uv tasks
  ansible.builtin.import_tasks: uv.yml
