---
- name: Install Pi Coding Agent
  block:
    - name: Ensure ~/.nvm/default-packages exists
      ansible.builtin.file:
        path: "{{ ansible_facts['env']['HOME'] }}/.nvm/default-packages"
        state: touch
        mode: "0644"
        modification_time: preserve
        access_time: preserve

    - name: Add pi-coding-agent to nvm default-packages
      ansible.builtin.lineinfile:
        path: "{{ ansible_facts['env']['HOME'] }}/.nvm/default-packages"
        line: "@earendil-works/pi-coding-agent"

    - name: Check current Pi version
      ansible.builtin.shell: source ~/.nvm/nvm.sh && pi --version
      args:
        executable: /bin/bash
      register: devtools_pi_version
      changed_when: false
      failed_when: false

    - name: Install Pi when missing
      ansible.builtin.shell: source ~/.nvm/nvm.sh && npm install -g @earendil-works/pi-coding-agent
      args:
        executable: /bin/bash
      when: devtools_pi_version.rc != 0
      changed_when: true
