---
- name: Download Nerd fonts
  ansible.builtin.git:
    repo: "https://github.com/ryanoasis/nerd-fonts.git"
    dest: "/tmp/nerd-fonts"
    depth: 1
    force: true
    version: "{{ nerd_fonts.version }}"

- name: Install Nerd fonts
  ansible.builtin.shell:
    cmd: "/tmp/nerd-fonts/install.sh {{ item }}"
  loop: "{{ nerd_fonts.fonts }}"
  notify:
    - Update font cache
