---
- name: Install cloud CLI packages
  community.general.homebrew:
    name:
      - awscli
      - azure-cli
      - oci-cli
    state: present
    path: "/home/linuxbrew/.linuxbrew/bin:/opt/homebrew/bin:/usr/local/bin:{{ ansible_facts['env']['PATH'] }}"
