---
- name: Install Kubernetes tools
  ansible.builtin.import_tasks: tasks/k8s.yml

- name: Install Hashicorp stack
  ansible.builtin.import_tasks: tasks/hashicorp.yml

- name: Install Cloud cli
  ansible.builtin.import_tasks: tasks/cloud.yml

- name: Install DevOps tools
  ansible.builtin.import_tasks: tasks/tools.yml
