---
- name: Install DevOps tools
  community.general.homebrew:
    name: "{{ item }}"
    state: present
    path: "/home/linuxbrew/.linuxbrew/bin:/opt/homebrew/bin:/usr/local/bin:{{ ansible_facts['env']['PATH'] }}"
  loop:
    - hey
    - dive
    - mintoolkit
