---
- name: Install VS Code
  become: true

  block:
    - name: Download VS Code .deb package
      get_url:
        url: "https://go.microsoft.com/fwlink/?LinkID=760868"
        dest: "/tmp/code.deb"

    - name: Install VS Code using apt
      apt:
        deb: "/tmp/code.deb"
        state: present
      register: result
