---
- name: Install VS Code
  become: true

  block:
    - name: Download VS Code .deb package
      ansible.builtin.get_url:
        url: "https://go.microsoft.com/fwlink/?LinkID=760868"
        dest: "/tmp/code.deb"
        mode: "u=rw,g=r,o=r"

    - name: Install VS Code using apt
      ansible.builtin.apt:
        deb: "/tmp/code.deb"
        state: present
      register: result
