---
- name: Install Gleam
  block:
    - name: Check current version
      ansible.builtin.command: "gleam --version"
      register: version
      changed_when: false
      failed_when: false

    - name: Get latest release version
      ansible.builtin.uri:
        method: GET
        url: https://api.github.com/repos/gleam-lang/gleam/releases/latest
      register: release

    - name: Register versions
      ansible.builtin.set_fact:
        current: "v{{ (version.rc | int == 0) | ternary(version.stdout | split | last, '') }}"
        latest: "{{ release.json.tag_name }}"

    - name: Install new version
      when: latest != current
      block:
        - name: Download package
          ansible.builtin.get_url:
            url: >
              {{
                release.json.assets
                | map(attribute='browser_download_url')
                | select('match', '^.*-' + ansible_architecture + '-.*-linux-.*\.tar\.gz$')
                | first
              }}
            dest: /tmp
            mode: "u=rw,g=r,o=r"
          register: downloaded

        - name: Create installation directory
          ansible.builtin.file:
            path: "{{ gleam_install_dir }}"
            state: directory
            mode: "u=rwx,g=rx,o=rx"

        - name: Unpack package
          ansible.builtin.unarchive:
            src: "{{ downloaded.dest }}"
            dest: "{{ gleam_install_dir }}"
            remote_src: true
