---
- name: Install Homebrew
  block:
    - name: Check current Homebrew version
      ansible.builtin.command: /home/linuxbrew/.linuxbrew/bin/brew --version
      register: system_brew_version
      changed_when: false
      failed_when: false

    - name: Get latest Homebrew release
      ansible.builtin.uri:
        method: GET
        url: https://api.github.com/repos/Homebrew/brew/releases/latest
      register: system_brew_release

    - name: Register versions
      ansible.builtin.set_fact:
        system_current_brew: >-
          {{ (system_brew_version.rc | int == 0) | ternary(
            system_brew_version.stdout_lines[0] | regex_replace('^Homebrew ([0-9.]+).*', '\1'),
            ''
          ) }}
        system_latest_brew: "{{ system_brew_release.json.tag_name }}"

    - name: Install latest Homebrew
      when: system_latest_brew != system_current_brew
      block:
        - name: Download Homebrew install script
          ansible.builtin.get_url:
            url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
            dest: /tmp/brew_install.sh
            mode: "u=rwx,g=rx,o=rx"

        - name: Run Homebrew install script
          ansible.builtin.command: /tmp/brew_install.sh
          environment:
            NONINTERACTIVE: "1"
          changed_when: true

        - name: Clean up install script
          ansible.builtin.file:
            path: /tmp/brew_install.sh
            state: absent
