---
- name: Setup system settings
  ansible.builtin.import_tasks: tasks/settings.yml

- name: Install system packages
  ansible.builtin.import_tasks: tasks/packages.yml

- name: Install Homebrew
  ansible.builtin.import_tasks: tasks/brew.yml

- name: Install GAH
  ansible.builtin.import_tasks: tasks/gah.yml

- name: Install Nerd Fonts
  ansible.builtin.import_tasks: tasks/nerd_fonts.yml

- name: Install ZSH
  ansible.builtin.import_tasks: tasks/zsh.yml

- name: Install Neovim
  ansible.builtin.import_tasks: tasks/neovim.yml

- name: Install Yazi
  ansible.builtin.import_tasks: tasks/yazi.yml
