---
- name: Set Nerd Fonts configuration
  ansible.builtin.set_fact:
    system_nerd_fonts:
      # version: "HEAD"
      version: "v3.3.0"
      fonts:
        - Agave
        - AnonymousPro
        - Arimo
        - AurulentSansMono
        - BitstreamVeraSansMono
        - CascadiaCode
        - CodeNewRoman
        - ComicShannsMono
        - Cousine
        - DaddyTimeMono
        - DejaVuSansMono
        - DroidSansMono
        - EnvyCodeR
        - FantasqueSansMono
        - FiraCode
        - FiraMono
        - Go-Mono
        - Hack
        - Hasklig
        - Hermit
        - IBMPlexMono
        - Inconsolata
        - InconsolataGo
        - InconsolataLGC
        - Iosevka
        - IosevkaTerm
        - JetBrainsMono
        - Lekton
        - LiberationMono
        - Lilex
        - Meslo
        - Monofur
        - Monoid
        - Mononoki
        - MPlus
        - Noto
        - OpenDyslexic
        - Overpass
        - ProFont
        - RobotoMono
        - ShareTechMono
        - SourceCodePro
        - SpaceMono
        - NerdFontsSymbolsOnly
        - Terminus
        - Tinos
        - Ubuntu
        - UbuntuMono
        - VictorMono
        - iA-Writer

- name: Check Nerd Fonts version marker
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.nerd-fonts"
  register: system_nerd_fonts_marker

- name: Read installed Nerd Fonts version
  ansible.builtin.slurp:
    src: "{{ ansible_env.HOME }}/.nerd-fonts"
  register: system_nerd_fonts_installed
  when: system_nerd_fonts_marker.stat.exists

- name: Set installed Nerd Fonts version
  ansible.builtin.set_fact:
    system_installed_nerd_fonts_version: >-
      {{ system_nerd_fonts_marker.stat.exists | ternary(
        system_nerd_fonts_installed.content | b64decode | trim, ''
      ) }}

- name: Install Nerd Fonts
  when: system_installed_nerd_fonts_version != system_nerd_fonts.version
  block:
    - name: Download Nerd fonts
      ansible.builtin.git:
        repo: "https://github.com/ryanoasis/nerd-fonts.git"
        dest: "/tmp/nerd-fonts"
        depth: 1
        force: true
        version: "{{ system_nerd_fonts.version }}"

    - name: Install Nerd fonts
      ansible.builtin.command:
        cmd: "/tmp/nerd-fonts/install.sh {{ item }}"
      loop: "{{ system_nerd_fonts.fonts }}"
      changed_when: true
      notify:
        - Update font cache

    - name: Record installed Nerd Fonts version
      ansible.builtin.copy:
        content: "{{ system_nerd_fonts.version }}"
        dest: "{{ ansible_env.HOME }}/.nerd-fonts"
        mode: "0644"
