---
- name: Install Packages
  block:
    - name: Update apt cache
      become: true
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_facts['os_family'] == 'Debian'

    - name: Apt packages
      become: true
      ansible.builtin.apt:
        name: "{{ system_packages }}"
        state: present
      when: ansible_facts['os_family'] == 'Debian'

    - name: Define a local bin path variable
      ansible.builtin.set_fact:
        system_local_bin: "{{ ansible_facts['env']['HOME'] }}/.local/bin"

    - name: Ensure local bin directory exists
      ansible.builtin.file:
        path: "{{ system_local_bin }}"
        state: directory
        mode: "u=rwx,g=rx,o=rx"

    - name: Create compatibility link
      become: false
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
        force: false
      loop:
        - src: "{{ lookup('pipe', 'which fdfind') }}"
          dest: "{{ system_local_bin }}/fd"
        - src: "{{ lookup('pipe', 'which batcat') }}"
          dest: "{{ system_local_bin }}/bat"
      ignore_errors: false
