---
- name: Setup System Settings
  become: true
  block:
    - name: Switch Capslock and Escape
      ansible.builtin.lineinfile:
        path: "/etc/default/keyboard"
        search_string: "XKBOPTIONS"
        line: "XKBOPTIONS=caps:swapescape"
        state: "present"

- name: Ensure local bin directory exists
  ansible.builtin.file:
    path: "{{ system_local_bin }}"
    state: directory
    mode: "u=rwx,g=rx,o=rx"
