---
- name: Install GAH
  vars:
    terminal_gah_install_script_url: https://raw.githubusercontent.com/get-gah/gah/refs/heads/master/tools/install.sh
    terminal_gah_install_script_path: /tmp/gah_install.sh
  block:
    - name: Check current GAH version
      ansible.builtin.command: gah version
      register: terminal_gah_version
      changed_when: false
      failed_when: false

    - name: Get latest GAH release version
      ansible.builtin.uri:
        method: GET
        url: https://api.github.com/repos/get-gah/gah/releases/latest
      register: terminal_gah_release

    - name: Register versions
      ansible.builtin.set_fact:
        terminal_current_gah: >-
          {{ (terminal_gah_version.rc | int == 0) | ternary(
            terminal_gah_version.stdout | split | last,
            ''
          ) }}
        terminal_latest_gah: "{{ terminal_gah_release.json.tag_name }}"

    - name: Install latest GAH
      when: terminal_latest_gah != terminal_current_gah
      block:
        - name: Download GAH install script
          ansible.builtin.get_url:
            url: "{{ terminal_gah_install_script_url }}"
            dest: "{{ terminal_gah_install_script_path }}"
            mode: "u=rwx,g=rx,o=rx"

        - name: Run GAH install script
          ansible.builtin.command: "{{ terminal_gah_install_script_path }}"
          changed_when: true

        - name: Clean up install script
          ansible.builtin.file:
            path: "{{ terminal_gah_install_script_path }}"
            state: absent
