---
- name: Download from git
  ansible.builtin.git:
    repo: "https://github.com/ryanoasis/nerd-fonts.git"
    dest: "/tmp/nerd-fonts"
    depth: 1
    force: yes

- name: Select fonts to install
  ansible.builtin.find:
    recurse: yes
    use_regex: yes
    paths: "/tmp/nerd-fonts"
    patterns:
      - '^.*?((?!Windows).)*?\.ttf$'
  register: fonts_to_install

- name: Install fonts
  ansible.builtin.copy:
    dest: "{{ ansible_env.HOME }}/.local/share/fonts/{{ item.path | basename }}"
    src: "{{ item.path }}"
    remote_src: yes
  loop: "{{ fonts_to_install.files }}"
  notify:
    - update font cache