---
name: Checks

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    steps:
      - name: Check out the codebase
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Super-Linter
        uses: super-linter/super-linter@9e863354e3ff62e0727d37183162c4a88873df41 # v8.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_ANSIBLE: true
          ANSIBLE_DIRECTORY: .
          VALIDATE_BASH: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_GITHUB_ACTIONS_ZIZMOR: true
          VALIDATE_YAML: true
          YAML_CONFIG_FILE: .yamllint.yml

  integration:
    name: Integration
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Running installation
        run: ./install.sh

      - name: Test for idempotence
        run: |
          trace_file=$(mktemp)
          ./install.sh | tee -a ${trace_file}
          tail ${trace_file} |
            grep -q 'changed=2.*failed=0' && \
            (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
