---
- name: Install CLI Tools
  become: true
  block:
    - name: Apt packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop: "{{ cli_tools.apt_packages }}"

    - name: Snap packages
      community.general.snap:
        name: "{{ item }}"
        state: present
      loop: "{{ cli_tools.snap_packages }}"
