---
galaxy_info:
  author: Peter Sukhenko
  description: >
    Install DevOps tool belt: Kubernetes (kubectl, minikube, helm, kubectx, k9s, lfk),
    HashiCorp stack (tfenv, consul, nomad, packer, vagrant),
    cloud CLIs (AWS, Azure, OCI), and auxiliary tools (hey, dive, mintoolkit).
  license: MIT
  min_ansible_version: "2.9"
  galaxy_tags:
    - devops
    - kubernetes
    - hashicorp
    - terraform
    - cloud
    - k9s
    - kubectx

dependencies: []
